apiVersion: apps/v1
kind: Deployment
metadata:
  name: latex-renderer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latex-renderer
  template:
    metadata:
      labels:
        app: latex-renderer
    spec:
      containers:
      - name: latex-renderer
        image: latex-renderer
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: latex-renderer
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: latex-renderer
